#!/bin/sh

stash_push() {
    STASH_NAME=pre-commit-$(date +%s)
    git diff --full-index --binary > /tmp/$STASH_NAME
    git stash push -q --keep-index -m $STASH_NAME
    STASH_NUM=$(git stash list | grep $STASH_NAME | sed -re 's/stash@\{(.*)\}.*/\1/')
}

stash_pop() {
    git apply --whitespace=nowarn < /tmp/$STASH_NAME 2> /dev/null
    rm /tmp/$STASH_NAME
    if [ -n "$STASH_NUM" ]; then
        git stash drop -q stash@{$STASH_NUM}
    fi
}

# Stash unstaged changes before running clippy and rustfmt
stash_push

# Check clippy lints
echo "\e[0;32m[INFO]: Checking clippy lints.\e[0;0m"

RUSTFLAGS="-Dwarnings" cargo clippy 2> /dev/null

if [ $? -ne 0 ]; then
    >&2 echo "\e[1;31m[ERROR]: Clippy lints failed!\e[0;0m"
    stash_pop
    exit 1;
fi

# Check format
echo "\e[0;32m[INFO]: Checking code format.\e[0;0m"

cargo fmt --all -- --check 1> /dev/null

if [ $? -ne 0 ]; then
    >&2 echo "\e[1;31m[ERROR]: Code is not properly formatted!\e[0;0m"
    stash_pop
    exit 1;
fi

stash_pop
